export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import React from "react";
import Head from "next/head";
import Script from "next/script";

import "@fortawesome/fontawesome-svg-core/styles.css"; // import Font Awesome CSS
import { config } from "@fortawesome/fontawesome-svg-core";

import { Header } from '../components/header/page';
import Footer from '../components/footer/page';
import '../styles/globals.css'

config.autoAddCss = false;
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
        <Script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-5514991570328030"
          crossOrigin="anonymous"
        />
      <body>
        <Header />
        {children}
        <Footer /> 
      </body>
    </html>
  )
}

